export enum EntityView {
  SHAPE_F = "shape_f",
  SHAPE_I = "shape_i",
  SHAPE_L = "shape_l",
  // SHAPE_N,
  // SHAPE_P,
  // SHAPE_T,
  // SHAPE_U,
  SHAPE_V = "shape_v",
  SHAPE_W = "shape_w",
  SHAPE_X = "shape_x",
  SHAPE_Y = "shape_y",
  // SHAPE_Z,
  ["5x5"] = "board5",
  ["5x6"] = "board6",
  BG = "https://raw.githubusercontent.com/petrkgn/katamino-game-angular/main/fon.png?raw=true",
}
